export const RECIPES = [
  {
    id: 0,
    name: "Creamy Pasta",
    mealType: "lunchDinner",
    description: "yummy pasta",
    image: require("../assets/images/food1.jpg"),
    cooktime: "20 mins",
    preptime: "10 mins",
    servings: 4,
    totaltime: "30 mins",
    ingredients: [
      "ingredient",
      "ingredient",
      "ingredient",
      "ingredient",
      "ingredient",
      "ingredient",
    ],
    directions: ["direction 1", "direction 2", "direction 3", "direction 4"],
  },
  {
    id: 1,
    name: "Chicken Salad",
    mealType: "lunchDinner",
    description: "healthy salad",
    cooktime: "20 mins",
    preptime: "10 mins",
    servings: 4,
    totaltime: "30 mins",
    image: require("../assets/images/food2.jpg"),
    ingredients: [
      "ingredient",
      "ingredient",
      "ingredient",
      "ingredient",
      "ingredient",
      "ingredient",
    ],
    directions: ["direction 1", "direction 2", "direction 3", "direction 4"],
  },
  {
    id: 2,
    name: "Fluffy Pancakes",
    mealType: "breakfast",
    description: "pancakessss",
    cooktime: "20 mins",
    preptime: "10 mins",
    servings: 4,
    totaltime: "30 mins",
    image: require("../assets/images/food4.jpg"),
    ingredients: [
      "ingredient",
      "ingredient",
      "ingredient",
      "ingredient",
      "ingredient",
      "ingredient",
    ],
    directions: ["direction 1", "direction 2", "direction 3", "direction 4"],
  },
  {
    id: 3,
    name: "Turkey Sandwich",
    mealType: "lunchDinner",
    cooktime: "20 mins",
    preptime: "10 mins",
    servings: 4,
    totaltime: "30 mins",
    description: "yummy sandwhich",
    image: require("../assets/images/food4.jpg"),
    ingredients: [
      "ingredient",
      "ingredient",
      "ingredient",
      "ingredient",
      "ingredient",
      "ingredient",
    ],
    directions: ["direction 1", "direction 2", "direction 3", "direction 4"],
  },
  {
    id: 4,
    name: "Berry Smoothie",
    mealType: "drinks",
    cooktime: "20 mins",
    preptime: "10 mins",
    servings: 4,
    totaltime: "30 mins",
    description: "fruity smoothie",
    image: require("../assets/images/food4.jpg"),
    ingredients: [
      "ingredient",
      "ingredient",
      "ingredient",
      "ingredient",
      "ingredient",
      "ingredient",
    ],
    directions: ["direction 1", "direction 2", "direction 3", "direction 4"],
  },
];
